/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora_ucss;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class vista_Calculadora extends javax.swing.JFrame {

    double promedio;
    DecimalFormat df = new DecimalFormat("##.##");
    public vista_Calculadora() {
        initComponents();
         setLocationRelativeTo(null);
        lc1.setVisible(false);
        lc2.setVisible(false);
        lc3.setVisible(false);
        lc4.setVisible(false);
        lc5.setVisible(false);
        lc6.setVisible(false);

        c1.setVisible(false);
        c2.setVisible(false);
        c3.setVisible(false);
        c4.setVisible(false);
        c5.setVisible(false);
        c6.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lc1 = new javax.swing.JLabel();
        lc2 = new javax.swing.JLabel();
        lc3 = new javax.swing.JLabel();
        lc4 = new javax.swing.JLabel();
        lc5 = new javax.swing.JLabel();
        lc6 = new javax.swing.JLabel();
        btnPromedio = new javax.swing.JButton();
        txtPromedioCon = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        c1 = new javax.swing.JTextField();
        c2 = new javax.swing.JTextField();
        c3 = new javax.swing.JTextField();
        c4 = new javax.swing.JTextField();
        c5 = new javax.swing.JTextField();
        c6 = new javax.swing.JTextField();
        txtNumcontinuas = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lp1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ep1 = new javax.swing.JTextField();
        ep2 = new javax.swing.JTextField();
        ep3 = new javax.swing.JTextField();
        fin = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnOk = new javax.swing.JButton();
        txtPromedioGeneral = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 360, -1, -1));

        jLabel5.setBackground(new java.awt.Color(0, 153, 153));
        jLabel5.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("PROMUCSS");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 30));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(0, 153, 153));
        jLabel9.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel9.setText("N° Continuas");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, -1));

        lc1.setText("Con1");
        jPanel3.add(lc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 37, -1, -1));

        lc2.setText("Con2");
        jPanel3.add(lc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 76, -1, -1));

        lc3.setText("Con3");
        jPanel3.add(lc3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 99, -1, -1));

        lc4.setText("Con4");
        jPanel3.add(lc4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 133, -1, -1));

        lc5.setText("Con5");
        jPanel3.add(lc5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 171, -1, -1));

        lc6.setText("Con6");
        jPanel3.add(lc6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 209, -1, -1));

        btnPromedio.setBackground(new java.awt.Color(0, 153, 153));
        btnPromedio.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnPromedio.setText("Promedio");
        btnPromedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromedioActionPerformed(evt);
            }
        });
        jPanel3.add(btnPromedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 251, -1, -1));

        txtPromedioCon.setBackground(new java.awt.Color(0, 153, 153));
        txtPromedioCon.setBorder(null);
        jPanel3.add(txtPromedioCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 245, 61, 23));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 274, 61, -1));

        c1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 42, 65, -1));

        c2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 73, 65, -1));

        c3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.add(c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 99, 65, -1));

        c4.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.add(c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 130, 65, -1));

        c5.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.add(c5, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 168, 65, -1));

        c6.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.add(c6, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 206, 65, -1));

        txtNumcontinuas.setBackground(new java.awt.Color(0, 153, 153));
        txtNumcontinuas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumcontinuasActionPerformed(evt);
            }
        });
        jPanel3.add(txtNumcontinuas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 40, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 200, 290));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(0, 153, 153));
        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PARCIALES");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 13, 156, -1));

        lp1.setText("EP1");
        jPanel1.add(lp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 40, -1, -1));

        jLabel6.setText("EP2");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 78, -1, -1));

        jLabel7.setText("EP3");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 116, -1, -1));

        jLabel8.setBackground(new java.awt.Color(0, 153, 153));
        jLabel8.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("FINAL");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 74, -1));

        ep1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.add(ep1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 37, 63, -1));

        ep2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.add(ep2, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 75, 63, -1));

        ep3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.add(ep3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 63, -1));

        fin.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.add(fin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 67, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 160, 200));

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));

        btnOk.setBackground(new java.awt.Color(0, 153, 153));
        btnOk.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnOk.setText("Ok ");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        txtPromedioGeneral.setBackground(new java.awt.Color(0, 153, 153));
        txtPromedioGeneral.setBorder(null);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(51, 51, 51)
                            .addComponent(btnOk))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addComponent(txtPromedioGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnOk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPromedioGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 160, 80));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 102, 102));
        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 70, -1));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setText("Curso");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jTextField1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 290, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPromedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromedioActionPerformed
        double co1 = Double.parseDouble(c1.getText());
        double co2 = Double.parseDouble(c2.getText());
        double co3 = Double.parseDouble(c3.getText());
        double co4 = Double.parseDouble(c4.getText());
        double co5 = Double.parseDouble(c5.getText());
        double co6 = Double.parseDouble(c6.getText());
        int num = Integer.parseInt(txtNumcontinuas.getText());

        promedio = (co1 + co2 + co3 + co4 + co5 + co6) / num;
        txtPromedioCon.setText("" + df.format(promedio));
    }//GEN-LAST:event_btnPromedioActionPerformed

    private void txtNumcontinuasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumcontinuasActionPerformed
        int num = Integer.parseInt(txtNumcontinuas.getText());
        if (num == 1) {
            lc1.setVisible(true);
            c1.setVisible(true);
            c2.setText("0");
            c3.setText("0");
            c4.setText("0");
            c5.setText("0");
            c6.setText("0");
        }
        if (num == 2) {
            lc1.setVisible(true);
            c1.setVisible(true);
            lc2.setVisible(true);
            c2.setVisible(true);

            c3.setText("0");
            c4.setText("0");
            c5.setText("0");
            c6.setText("0");
        }
        if (num == 3) {
            lc1.setVisible(true);
            c1.setVisible(true);
            lc2.setVisible(true);
            c2.setVisible(true);
            lc3.setVisible(true);
            c3.setVisible(true);

            c4.setText("0");
            c5.setText("0");
            c6.setText("0");
        }
        if (num == 4) {
            lc1.setVisible(true);
            c1.setVisible(true);
            lc2.setVisible(true);
            c2.setVisible(true);
            lc3.setVisible(true);
            c3.setVisible(true);
            lc4.setVisible(true);
            c4.setVisible(true);

            c5.setText("0");
            c6.setText("0");
        }
        if (num == 5) {
            lc1.setVisible(true);
            c1.setVisible(true);
            lc2.setVisible(true);
            c2.setVisible(true);
            lc3.setVisible(true);
            c3.setVisible(true);
            lc4.setVisible(true);
            c4.setVisible(true);
            lc5.setVisible(true);
            c5.setVisible(true);

            c6.setText("0");
        }
        if (num == 6) {
            lc1.setVisible(true);
            c1.setVisible(true);
            lc2.setVisible(true);
            c2.setVisible(true);
            lc3.setVisible(true);
            c3.setVisible(true);
            lc4.setVisible(true);
            c4.setVisible(true);
            lc5.setVisible(true);
            c5.setVisible(true);
            lc6.setVisible(true);
            c6.setVisible(true);
        }
    }//GEN-LAST:event_txtNumcontinuasActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        double p1 = Double.parseDouble(ep1.getText());
        double p2 = Double.parseDouble(ep2.getText());
        double p3 = Double.parseDouble(ep3.getText());
        double f = Double.parseDouble(fin.getText());

        double promeGeneral = Math.round((p1 * 0.1) + (p2 * 0.2) + (p3 * 0.2) + (f * 0.3) + (promedio * 0.2));

        txtPromedioGeneral.setText("" + df.format(promeGeneral));

        if (promeGeneral > 10.5) {
            JOptionPane.showMessageDialog(null, "Saco un promedio de " + df.format(promeGeneral) + "\n♦♦FELICIADES A APROBAD☺♦♦");
        } else {
            JOptionPane.showMessageDialog(null, "Saco un promedio de " + df.format(promeGeneral) + "\n♦♦USTED A DESAPROBAD◙♦♦\n:(");
        }
    }//GEN-LAST:event_btnOkActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        c2.setText("");
        c3.setText("");
        c4.setText("");
        c5.setText("");
        c6.setText("");
        c1.setText("");

        ep1.setText("");
        ep2.setText("");
        ep3.setText("");
        fin.setText("");

        txtNumcontinuas.setText("");
        txtPromedioCon.setText("");
        txtPromedioGeneral.setText("");

        lc1.setVisible(false);
        lc2.setVisible(false);
        lc3.setVisible(false);
        lc4.setVisible(false);
        lc5.setVisible(false);
        lc6.setVisible(false);

        c1.setVisible(false);
        c2.setVisible(false);
        c3.setVisible(false);
        c4.setVisible(false);
        c5.setVisible(false);
        c6.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vista_Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vista_Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vista_Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vista_Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vista_Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnPromedio;
    private javax.swing.JTextField c1;
    private javax.swing.JTextField c2;
    private javax.swing.JTextField c3;
    private javax.swing.JTextField c4;
    private javax.swing.JTextField c5;
    private javax.swing.JTextField c6;
    private javax.swing.JTextField ep1;
    private javax.swing.JTextField ep2;
    private javax.swing.JTextField ep3;
    private javax.swing.JTextField fin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lc1;
    private javax.swing.JLabel lc2;
    private javax.swing.JLabel lc3;
    private javax.swing.JLabel lc4;
    private javax.swing.JLabel lc5;
    private javax.swing.JLabel lc6;
    private javax.swing.JLabel lp1;
    private javax.swing.JTextField txtNumcontinuas;
    private javax.swing.JTextField txtPromedioCon;
    private javax.swing.JTextField txtPromedioGeneral;
    // End of variables declaration//GEN-END:variables
}
